class paragraphs{
    
    static paragraphs = [
        "The quick brown fox jumped over the lazy dog. The lazy dog was a stupid purple beast unworthy of the brown fox's attention. The dog died and as time went on the fox reminisced over reminisced over his time with the dog.",
        "In a valley where the wind braided secrets into the tall grass, a fox once tried to outrun his own shadow. Each morning he boasted to the river that he was quicker than thought itself, and each evening the river reflected him back—panting, dusted with burrs, humbled by the mirror of water. One day he noticed a small tortoise crossing the path he’d worn thin with pride. Laughing, the fox sprinted ahead, then circled back, then ahead again, until the sun slipped behind the hills and the valley dimmed. When the fox finally slowed, the tortoise was already at the cool edge of the stream, drinking quietly. The fox learned that speed is loud but steadiness arrives first—and the wind, pleased to have taught a lesson without a word, carried the story into the grass",
        "On the rim of a quiet pond lived a crow who collected shiny things, stacking them on a flat stone to prove he was “rich in wonders.” A heron passed by each dawn, patient as fog, fishing with empty claws and a full belly by noon. One day a storm scattered the crow’s treasures into the mud, and he wailed at the water for stealing his sparkle. The heron showed him how to watch the ripples, how to wait for what actually fed you. By dusk, the crow had only one bright pebble left—but he also had a fish and a calmer heart. From then on, he kept fewer trinkets and more time, and the pond kept his secrets for him.",
        "A moth bragged to the lantern about how fearless she was of light, circling closer with every boast. When her wings grew warm, she learned that courage without care is just another way to fall. The lantern kept glowing, but the moth kept her distance after that.",
        "A bear tried to scare winter away by shouting into the cold hills. The hills answered with silence, and the cold answered by staying. When the bear built a den instead, winter softened around him.",
        "A snail challenged the rain to a race across a leaf. The rain fell fast and left quickly, but the snail kept moving long after the leaf dried. The finish line belongs to whoever stays.",
        "A sparrow mocked the owl for blinking through daylight, calling it laziness. That night, lost in the dark, the sparrow learned how wisdom can look like weakness when you don’t know the hour.",
        "A river stone envied the mountain for its height. Over time, the stone found that it shaped the water instead of the sky, and the water shaped the land in return. Quiet power leaves deep marks.",
        "A cat counted the mice he’d never caught and called it bad luck. The mice counted the traps they’d never sprung and called it good sense. The house slept easier when both learned their math.",
        "A bee complained that the flowers were too far apart. The wind reminded her that distance is what lets gardens exist. The bee flew on, carrying a map she hadn’t known she had.",
        "A mirror cracked and thought itself broken beyond use. In its shards, the sparrows found ten new suns. What seems ruined can still scatter light.",
        "A wolf practiced howling alone until his voice grew strong but hollow. When he finally listened, the forest taught him harmonies he couldn’t make by himself.",
        "A seed argued with the soil about being buried. The soil stayed patient, and the seed learned that some beginnings feel like endings.",
        "A fish wanted the clouds for their freedom, leaping at every reflection. When the pond went still, the fish noticed the sky had been in the water all along.",
        "A clock in the village square boasted of keeping perfect time. The old tree nearby grew rings that laughed at seconds. Both were right about time in their own way.",
        "A hedgehog curled up to avoid every thorny path. One morning she uncurled and found the path had grown longer from waiting. Safe pauses are good; safe forever is not.",
        "A candle scolded the darkness for being everywhere. The darkness answered by making room for the flame. Light learns humility when it meets enough night.",
        "A crow hoarded echoes in the canyon, repeating every insult he’d heard. The canyon gave them back until the crow tried a song. Only then did the echoes change.",
        "A turtle painted her shell bright to look brave. The paint peeled in rain, but her steps stayed steady. Bravery kept better than color.",
        "A fox planned ten clever tricks for a single hunt. A rabbit practiced one good turn of speed. The rabbit ate clover at dusk; the fox ate his plans.",
        "A mountain stream complained that the sea took all its water. The sea sent clouds back upstream as thanks. Even what leaves can return changed.",
        "A firefly dimmed his light to fit in with the stars. The meadow grew darker, and he grew lonelier. When he shone again, the grass remembered how to glow.",
        "A donkey carried bells to sound important on the road. When the bells fell off, travelers finally heard the donkey’s steady steps—and trusted where they were going.",
        "Now this is the story all about how my life got flipped-turn upside down. and I'd like to take a minute, just sit right there. I'll tell you how I became the prince of a town called Bel-Air, In West Philadelphia, born and raised, on the playground is where I spent most of my days, Chillin' out, maxin, relaxin' all cool all while shooting some bball outside of the school, when a couple of guys who were up to no good started making trouble in my neighborhood. I got in one little fight and my mom got scared. She said, 'You're moving with your auntie and uncle in Bel-Air'",
        "'Now what are you laughing at? Look at it like this: I only hit her with that little horsewhip twice, there weren't even any marks... Please don't think me a cynic; I mean, I have a precise awareness of just what an infamous thing it was to do, and so on, and so forth; but you see, I also know for a fact that Marfa Petrovna actualy derived pleasure from my, as it were, enthusiasm.",
        "Pyotr Petrovich actually jumped. Everyone noticed this. (They remembered it later on.) Lebezyatnikov strode into the room.",
        "The glass door to my right is thrust open. A loud crashing sound shortly follows, and a man, clad in all black rushes in. His skin is ghastly pale, and he has hair the color of night. He rapidly clicks a pen and throws himself onto the leather chair furthest from me, a chair that is just one of many that sit adjacent to the long marble table.",
        "I don’t know what dumbass decided to install faulty bugs all over the place, but here we are. It is common knowledge amongst our offices nowadays that the previous generation of bugs have a fatal flaw, they emit an ear piercing noise when they are close to running out of battery. The people who designed them were morons playing with the public’s money, but the higher ups who thought it’d be a good idea to put them in the field were absolute idiots. As a result, my job has been mostly reduced to taking back these faulty wires.",
        "The front door led immediately to the living room, which was only illuminated by a dim light bleeding in from the kitchen. I could see a flat screen TV mounted to the wall, around 80 inches if I had to guess, and a large leather couch.",
        "Welcome to the Huskie Hackers! Huskie Hackers is a computer science club at Northern Illinois University dedicated to building coding skills through teamwork, creativity, and fun. We participate in competitive hackathons and game jams, and we also run smaller, low-pressure projects outside of coursework to help members explore new ideas and technologies.",
        "At NIU, getting real team-coding experience during classes can be challenging, so we create a collaborative, supportive environment where you can learn, experiment, and grow alongside other passionate programmers. Whether you’re a beginner or experienced coder, we make building cool projects exciting again.",
        "Now, what serves the will as the objective ground for its action upon itself is an end, and if it is given by reason alone it must be an end for all rational beings. On the other hand, what contains the ground of the possibility of the action that leads to the end is called the means. The subjective ground of desire is the action-driver, while the objective ground of volition is the motive.",
        "I know he swapped those numbers. I knew it was 1216. One after Magna Carta, as if I could ever make such a mistake. Never. I just... I just couldn't prove it. He covered his tracks, he got that idiot at the coffee shop to lie for him. You think this is bad? This? This chicanery? He's done worse. That billboard. You think a man just happens to fall like that? NO! he orchestrated it. HE DEFECATED THROUGH A SUNROOF! AND I SAVED HIM! And I shouldn't've. I took him into my own firm. What was I thinking? He'll never change, he'll never change. Ever since he was nine, always the same! Couldn't keep his hands out of the cash drawer. But not our Jimmy! Couldn't be precious Jimmy! Stealing them blind. And HE gets to be a lawyer? What a sick joke! I should've stopped him when I had the chance. And you, you have to stop him!",
        "Hi my name is Ebony Dark'ness Dementia Raven Way and I have long ebony black hair (that's how I got my name) with purple streaks and red tips that reaches my mid-back and icy blue eyes like limpid tears and a lot of people tell me I look like Amy Lee (AN: if u don't know who she is get da hell out of here!). I'm not related to Gerard Way but I wish I was because he's a major fucking hottie. I'm a vampire but my teeth are straight and white. I have pale white skin. I'm also a witch, and I go to a magic school called Hogwarts in England where I'm in the seventh year (I'm seventeen). I'm a goth (in case you couldn't tell) and I wear mostly black. I love Hot Topic and I buy all my clothes from there. For example today I was wearing a black corset with matching lace around it and a black leather miniskirt, pink fishnets and black combat boots. I was wearing black lipstick, white foundation, black eyeliner, and red eye shadow. I was walking outside Hogwarts. It was snowing and raining so there was no sun, which I was very happy about it. A lot of preps stared at me. I put up my middle finger at them.",
        "His palms are sweaty, knees weak, arms are heavy There's vomit on his sweater already, mom's spaghetti He's nervous, but on the surface he looks calm and ready to drops bombs, but he keeps on forgetting what he wrote down, the whole crowd goes so loud, he opens his mouth but the words won't come out. He's chokin, how? Everybody's jokin now. The clock's run out, time's up, over - BLAOW! Snap back to reality, OHH! there goes gravity, OHH! there goes Rabbit, he choked, he's so mad, but he won't. Give up that easy nope, he won't have it. He knows, his whole back's to these ropes, it don't matter, he's dope. He knows that, but he's broke. He's so sad that he knows when he goes back to this mobile home, that's when it's back to the lab again, yo. This whole rhapsody, better go capture this moment and hope it don't pass him",
        "We had a good thing, you stupid son of a bitch. We had Fring. We had a lab. We had everything we needed and it all ran like clockwork. You could've shut your mouth, cooked and much money as you ever needed. It was perfect. But no, you just had to blow it up. You and your pride and your ego. You just had to be the man. If you'd done your job, known your place, we'd all be fine right now."
    ];





}